positive:
- winning: ğŸ˜‡ğŸ˜ğŸ¤©ğŸ¥³ğŸ¤‘ğŸ¤“ğŸ¤ ğŸ«¡
- cheeky: ğŸ˜ğŸ˜‰ğŸ˜‹ğŸ˜›ğŸ˜ğŸ˜œğŸ¤ª
- happy: ğŸ™‚ğŸ™ƒğŸ˜€ğŸ˜ƒğŸ˜ğŸ˜„ğŸ˜†ğŸ˜…ğŸ˜‚ğŸ¤£
- content: ğŸ˜Œâ˜ºï¸ğŸ˜ŠğŸ¤—ğŸ¥°
- amorous: ğŸ˜—ğŸ˜™ğŸ˜šğŸ˜˜ğŸ˜
neutral:
- shy: ğŸ«¢ğŸ¤­
- emotional: ğŸ¥²ğŸ¥¹
- reserved: ğŸ˜¶ğŸ˜ğŸ˜‘ğŸ«¥
- thoughtful: ğŸ¤”ğŸ§
- opinionated: ğŸ¤¨ğŸ¤ğŸ™„ğŸ¤«ğŸ¤¥ğŸ¥¸ğŸ˜¶â€ğŸŒ«ï¸
negative:
- resigned: ğŸ˜’ğŸ˜ğŸ˜”ğŸ˜®â€ğŸ’¨ğŸ˜¤
- shocked: ğŸ˜¦ğŸ˜§ğŸ˜®ğŸ˜¯ğŸ˜²ğŸ˜³ğŸ¤¯
- unhappy: ğŸ«¤ğŸ˜•ğŸ™â˜¹ï¸ğŸ˜¥ğŸ˜¢ğŸ˜­
- frustrated: ğŸ˜ŸğŸ˜£ğŸ˜–ğŸ˜“ğŸ˜«ğŸ˜©
- stressed: ğŸ˜¬ğŸ¥ºğŸ«£ğŸ«¨ğŸ˜µâ€ğŸ’«ğŸ˜µ
- fearful: ğŸ˜¨ğŸ˜°ğŸ˜±
- angry: ğŸ˜ ğŸ˜¡ğŸ¤¬ğŸ‘¿
physical:
- tired: ğŸ¥±ğŸ˜´ğŸ¤¤ğŸ˜ª
- sick: ğŸ¥´ğŸ¤¢ğŸ¤®
- heat: ğŸ« ğŸ¥µğŸ¥¶
- unwell: ğŸ˜·ğŸ¤§ğŸ¤’ğŸ¤•
common:
- body:
