  - ğŸ¥³: partying face
  - ğŸ˜: smiling face with sunglasses
  - ğŸ¤©: star-struck
  - ğŸ¤‘: money-mouth face
  - ğŸ¤“: nerd face
  - ğŸ¤ : cowboy hat face
  - ğŸ˜‡: smiling face with halo
  - ğŸ«¡: saluting face
  - ğŸ˜: smirking face
  - ğŸ˜‰: winking face
  - ğŸ˜‹: face savoring food
  - ğŸ˜›: face with tongue
  - ğŸ˜: squinting face with tongue
  - ğŸ˜œ: winking face with tongue
  - ğŸ¤ª: zany face
  - ğŸ™‚: slightly smiling face
  - ğŸ™ƒ: upside-down face
  - ğŸ˜€: grinning face
  - ğŸ˜ƒ: grinning face with big eyes
  - ğŸ˜: beaming face with smiling eyes
  - ğŸ˜„: grinning face with smiling eyes
  - ğŸ˜†: grinning squinting face
  - ğŸ˜…: smiling face with sweat
  - ğŸ˜‚: face with tears of joy
  - ğŸ¤£: rolling on the floor laughing
  - ğŸ˜Œ: relieved face
  - â˜ºï¸: smiling face
  - ğŸ˜Š: smiling face with smiling eyes
  - ğŸ¤—: hugging face
  - ğŸ¥°: smiling face with hearts
  - ğŸ˜—: kissing face
  - ğŸ˜™: kissing face with smiling eyes
  - ğŸ˜š: kissing face with closed eyes
  - ğŸ˜˜: face blowing a kiss
  - ğŸ˜: heart eyes
  - ğŸ«¢: face with open eyes and hand over mouth
  - ğŸ¤­: face with hand over mouth
  - ğŸ¥²: smiling face with tear
  - ğŸ¥¹: face holding back tears
  - ğŸ˜¶: face without mouth
  - ğŸ˜: neutral face
  - ğŸ˜‘: expressionless face
  - ğŸ«¥: dotted line face
  - ğŸ¤”: thinking face
  - ğŸ§: face with monocle
  - ğŸ¤¨: face with raised eyebrow
  - ğŸ¤: zipper-mouth face
  - ğŸ™„: face with rolling eyes
  - ğŸ¤«: shushing face
  - ğŸ¤¥: lying face
  - ğŸ¥¸: disguised face
  - ğŸ˜¶â€ğŸŒ«ï¸: face in clouds
  - ğŸ˜’: unamused face
  - ğŸ˜: disappointed face
  - ğŸ˜”: pensive face
  - ğŸ˜®â€ğŸ’¨: face exhaling
  - ğŸ˜¤: face with steam from nose
  - ğŸ˜¯: hushed face
  - ğŸ˜®: face with open mouth
  - ğŸ˜¦: frowning face with open mouth
  - ğŸ˜§: anguished face
  - ğŸ˜²: astonished face
  - ğŸ˜³: flushed face
  - ğŸ¤¯: exploding head
  - ğŸ«¤: face with diagonal mouth
  - ğŸ˜•: confused face
  - ğŸ™: slightly frowning face
  - â˜¹ï¸: frowning face
  - ğŸ˜¥: sad but relieved face
  - ğŸ˜¢: crying face
  - ğŸ˜­: loudly crying face
  - ğŸ˜Ÿ: worried face
  - ğŸ˜£: persevering face
  - ğŸ˜–: confounded face
  - ğŸ˜“: downcast face with sweat
  - ğŸ˜«: tired face
  - ğŸ˜©: weary face
  - ğŸ˜¬: grimacing face
  - ğŸ¥º: pleading face
  - ğŸ«£: face with peeking eye
  - ğŸ«¨: shaking face
  - ğŸ˜µâ€ğŸ’«: face with spiral eyes
  - ğŸ˜µ: dizzy face
  - ğŸ˜¨: fearful face
  - ğŸ˜°: anxious face with sweat
  - ğŸ˜±: face screaming in fear
  - ğŸ˜ : angry face
  - ğŸ˜¡: pouting face
  - ğŸ¤¬: face with symbols on mouth
  - ğŸ‘¿: angry face with horns
  - ğŸ¥±: yawning face
  - ğŸ˜´: sleeping face
  - ğŸ¤¤: drooling face
  - ğŸ˜ª: sleepy face
  - ğŸ¥´: woozy face
  - ğŸ¤¢: nauseated face
  - ğŸ¤®: face vomiting
  - ğŸ« : melting face
  - ğŸ¥µ: hot face
  - ğŸ¥¶: cold face
  - ğŸ˜·: face with medical mask
  - ğŸ¤§: sneezing face
  - ğŸ¤’: face with thermometer
  - ğŸ¤•: face with head-bandage
  